# Support Vector Machine(SVM)

In [14]:
import pandas as pd
df=pd.read_csv("Employee_Attrition.csv")# attrition =emplloyee job ma rehshe ke nahi
df.isna().sum()
df.head()

,Employee_ID,Age,Monthly_Income,Years_at_Company,Job_Role,Work_Life_Balance,Overtime,Job_Satisfaction,Distance_From_Home,Education,Attrition
0,1,29,23278,8,Manager,Poor,Yes,1,22,Postgraduate,1
1,2,56,31395,18,HR,Poor,Yes,1,7,School,1
2,3,54,98907,0,Manager,Excellent,No,2,15,Postgraduate,0
3,4,39,20851,5,HR,Good,No,2,7,Graduate,0
4,5,28,32156,12,Developer,Good,No,3,26,School,0

In [15]:
df.drop(columns="Employee_ID",inplace=True)

df=pd.get_dummies(data=df,drop_first=True)
df.head()

,Age,Monthly_Income,Years_at_Company,Job_Satisfaction,Distance_From_Home,Attrition,Job_Role_Developer,Job_Role_HR,Job_Role_Manager,Work_Life_Balance_Good,Work_Life_Balance_Poor,Overtime_Yes,Education_Postgraduate,Education_School
0,29,23278,8,1,22,1,False,False,True,False,True,True,True,False
1,56,31395,18,1,7,1,False,True,False,False,True,True,False,True
2,54,98907,0,2,15,0,False,False,True,False,False,False,True,False
3,39,20851,5,2,7,0,False,True,False,True,False,False,False,False
4,28,32156,12,3,26,0,True,False,False,True,False,False,False,True

In [16]:
df.columns
x=df[['Age', 'Monthly_Income', 'Years_at_Company', 'Job_Satisfaction',
       'Distance_From_Home','Job_Role_Developer', 'Job_Role_HR',
       'Job_Role_Manager', 'Work_Life_Balance_Good', 'Work_Life_Balance_Poor',
       'Overtime_Yes', 'Education_Postgraduate', 'Education_School']]
y=df["Attrition"]

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(200, 13)
(50, 13)
(200,)
(50,)

In [19]:
from sklearn.svm import SVC
model=SVC(C=10,random_state=42)#c=margin

In [20]:
model.fit(x_train,y_train)

SVC(C=10, random_state=42)

In [24]:
y_pred=model.predict(x_test)

In [27]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[47,  0],
       [ 3,  0]])

In [28]:
tn=cm[0][0]
fp=cm[0][1]
fn=cm[1][0]
tp=cm[1][1]
print("tn ",tn)
print("fp ",fp)
print("fn ",fn)
print("tp ",tp)

tn  47
fp  0
fn  3
tp  0

In [30]:
total=tn+tp+fn+fp
acc=(tn+tp)/total
error=(fn+fp)/total
sensi=tp/(tp+fn)
spe=tn/(tn+fp)
prec=tp/(tp+fp)
print("accuracy :",acc)
print("Error_rate :",error)
print("sensitivity :",sensi)
print("specifivity :",spe)
print("precison :",prec)
df.head(0)

accuracy : 0.94
Error_rate : 0.06
sensitivity : 0.0
specifivity : 1.0
precison : nan

C:\Users\LJENG\AppData\Local\Temp\ipykernel_8676\339822493.py:6: RuntimeWarning: invalid value encountered in scalar divide
  prec=tp/(tp+fp)

Empty DataFrame
Columns: [Age, Monthly_Income, Years_at_Company, Job_Satisfaction, Distance_From_Home, Attrition, Job_Role_Developer, Job_Role_HR, Job_Role_Manager, Work_Life_Balance_Good, Work_Life_Balance_Poor, Overtime_Yes, Education_Postgraduate, Education_School]
Index: []

In [37]:
pred=model.predict([[30,45000,5,3,10,1,0,0,1,0,1,0,0]])
pred

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

array([0])

In [ ]:
1.knn

In [67]:
import pandas as pd
df=pd.read_csv("Employee_Attrition.csv")# attrition =emplloyee job ma rehshe ke nahi
df.isna().sum()
df.head()

,Employee_ID,Age,Monthly_Income,Years_at_Company,Job_Role,Work_Life_Balance,Overtime,Job_Satisfaction,Distance_From_Home,Education,Attrition
0,1,29,23278,8,Manager,Poor,Yes,1,22,Postgraduate,1
1,2,56,31395,18,HR,Poor,Yes,1,7,School,1
2,3,54,98907,0,Manager,Excellent,No,2,15,Postgraduate,0
3,4,39,20851,5,HR,Good,No,2,7,Graduate,0
4,5,28,32156,12,Developer,Good,No,3,26,School,0

In [68]:
df.drop(columns="Employee_ID",inplace=True)

df=pd.get_dummies(data=df,drop_first=True)
df.head()

,Age,Monthly_Income,Years_at_Company,Job_Satisfaction,Distance_From_Home,Attrition,Job_Role_Developer,Job_Role_HR,Job_Role_Manager,Work_Life_Balance_Good,Work_Life_Balance_Poor,Overtime_Yes,Education_Postgraduate,Education_School
0,29,23278,8,1,22,1,False,False,True,False,True,True,True,False
1,56,31395,18,1,7,1,False,True,False,False,True,True,False,True
2,54,98907,0,2,15,0,False,False,True,False,False,False,True,False
3,39,20851,5,2,7,0,False,True,False,True,False,False,False,False
4,28,32156,12,3,26,0,True,False,False,True,False,False,False,True

In [69]:
df.columns
y=df["Attrition"]
x=df[['Age', 'Monthly_Income', 'Years_at_Company', 'Job_Satisfaction',
       'Distance_From_Home','Job_Role_Developer', 'Job_Role_HR',
       'Job_Role_Manager', 'Work_Life_Balance_Good', 'Work_Life_Balance_Poor',
       'Overtime_Yes', 'Education_Postgraduate', 'Education_School']]

In [70]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(200, 13)
(50, 13)
(200,)
(50,)

In [73]:
from sklearn.neighbors import KNeighborsClassifier
accuracy=[]
kn=[]
for i in range(1,26):
    nn=KNeighborsClassifier(n_neighbors=i)
    nn.fit(x_train,y_train)
    y_pred=nn.predict(x_test)
    from sklearn.metrics import confusion_matrix
    cm=confusion_matrix(y_test,y_pred)
    tn=cm[0][0]
    fp=cm[0][1]
    fn=cm[1][0]
    tp=cm[1][1]
    total=tn+tp+fn+fp
    acc=(tn+tp)/total
    print("accuracy :",acc)
    accuracy.append(acc)
    kn.append(i)
ACCURAXY=(max(accuracy))
maxK=accuracy.index(max(accuracy))
print(ACCURAXY)
print(maxK+1)

accuracy : 0.86
accuracy : 0.94
accuracy : 0.94
accuracy : 0.94
accuracy : 0.94
accuracy : 0.94
accuracy : 0.94
accuracy : 0.94
accuracy : 0.94
accuracy : 0.94
accuracy : 0.94
accuracy : 0.94
accuracy : 0.94
accuracy : 0.94
accuracy : 0.94
accuracy : 0.94
accuracy : 0.94
accuracy : 0.94
accuracy : 0.94
accuracy : 0.94
accuracy : 0.94
accuracy : 0.94
accuracy : 0.94
accuracy : 0.94
accuracy : 0.94
0.94
2

In [76]:
nn=KNeighborsClassifier(n_neighbors=2)
nn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=2)

In [77]:
y_pred=nn.predict(x_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[47,  0],
       [ 3,  0]])

In [80]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=150,random_state=42,criterion="entropy",max_depth=12)
rf

RandomForestClassifier(criterion='entropy', max_depth=12, n_estimators=150,
                       random_state=42)

In [81]:
rf.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=12, n_estimators=150,
                       random_state=42)

In [82]:
# p=rf.predict([[]])